jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setting up JDK8
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Running Kafka
      run: docker-compose -f docker/compose/kafka-schema-registry.yml up -d && sleep
        10
    - continue-on-error: true
      name: Building and testing the changes
      run: mvn clean test
name: CI Build
on:
  repository_dispatch:
    types: trigger-ga___main.yml
